FORMAT: 1A
HOST: https://aplicacao.api.teste/

# Clientes e departamentos

Cadastramento de clientes e departamentos genericos

# API de cadastro geral

## Listar clientes [/clientes]

*https://private-ca8518-leobossgomes.apiary-mock.com/clientes*

### Metodo GET [GET]

+ Response 200 (application/json)

        {
            "status": "sucesso",
            "data": [
                {
                    "id": "1",
                    "nome": "Robertinho",
                    "telefone": "9875-6432",
                    "email": "roberto@gmail.com",
                    "cpf": "449.756.315-15",
                    "rua": "rua natal",
                    "numero": "96",
                    "complemento": "apartamento 106",
                    "cep": "89107-000",
                    "uf": "SC"
                },
                {
                    "id": "2",
                    "nome": "Cleiton",
                    "telefone": "1643-7842",
                    "email": "cleiton@gmail.com",
                    "cpf": "456.123.789-00",
                    "rua": "rua peixoto",
                    "numero": "15",
                    "complemento": "",
                    "cep": "89107-000",
                    "uf": "SC"
                }
            ]  
        }

## Retornar dados de um cliente [/clientes/{id}]

*https://private-ca8518-leobossgomes.apiary-mock.com/clientes/id*

### Metodo GET, parametro id[GET]

+ Parameters
    + id (number) - ID do cliente

+ Response 200 (application/json)

        {
            "status": "sucesso",
            "data": {
                "id": "1",
                "nome": "Robertinho",
                "telefone": "9875-6432",
                "email": "roberto@gmail.com",
                "cpf": "449.756.315-15",
                "rua": "rua natal",
                "numero": "96",
                "complemento": "apartamento 106",
                "cep": "89107-000",
                "uf": "SC"
            }
        }
        
## Cria cliente [/criacliente]

*https://private-ca8518-leobossgomes.apiary-mock.com/criacliente*

### Metodo POST [POST]

+ Request (application/json)

        {
            "nome": "Cleiton",
            "telefone": "1643-7842",
            "email": "cleiton@gmail.com",
            "cpf": "456.123.789-00",
            "rua": "rua peixoto",
            "numero": "15",
            "complemento": "",
            "cep": "89107-000",
            "uf": "SC"
        }

+ Response 201 (application/json)

        {
            "status": "sucesso",
            "data": {
                "nome": "Cleiton",
                "telefone": "1643-7842",
                "email": "cleiton@gmail.com",
                "cpf": "456.123.789-00",
                "rua": "rua peixoto",
                "numero": "15",
                "complemento": "",
                "cep": "89107-000",
                "uf": "SC"
            }
        }

## Mudar dados de um cliente já existente [/updatecliente/{id}]

*https://private-ca8518-leobossgomes.apiary-mock.com/updatecliente/id*

### Metodo PUT, parametro id [PUT]

+ Parameters
    + id

+ Request (application/json)

        {
            "nome": "Cleiton",
            "telefone": "1643-7842",
            "email": "cleiton@gmail.com",
            "cpf": "456.123.789-00",
            "rua": "rua peixoto",
            "numero": "15",
            "complemento": "",
            "cep": "89107-000",
            "uf": "SC"
        }

+ Response 200 (application/json)

        {
            "status": "sucesso",
            "data": {
                "nome": "Cleiton",
                "telefone": "1643-7842",
                "email": "cleiton@gmail.com",
                "cpf": "456.123.789-00",
                "rua": "rua peixoto",
                "numero": "15",
                "complemento": "",
                "cep": "89107-000",
                "uf": "SC"
            }
        }

## Excluir Cliente [/deletecliente/{id}]

*https://private-ca8518-leobossgomes.apiary-mock.com/deletecliente/id*

### Metodo delete, parametro id [DELETE]

+ Parameters
    + id

+ Request (application/json)

        {
            "nome": "Cleiton",
            "telefone": "1643-7842",
            "email": "cleiton@gmail.com",
            "cpf": "456.123.789-00",
            "rua": "rua peixoto",
            "numero": "15",
            "complemento": "",
            "cep": "89107-000",
            "uf": "SC"
        }

+ Response 200 (application/json)

        {
            "status": "sucesso",
            "data": {
                "nome": "Cleiton",
                "telefone": "1643-7842",
                "email": "cleiton@gmail.com",
                "cpf": "456.123.789-00",
                "rua": "rua peixoto",
                "numero": "15",
                "complemento": "",
                "cep": "89107-000",
                "uf": "SC"
            }
        }


# Departamentos

## Listar departamentos [/departamentos]

*https://private-ca8518-leobossgomes.apiary-mock.com/departamentos*

### Metodo GET [GET]

+ Response 200 (application/json)

        {
            "status": "sucesso",
            "data": [
                {
                    "id_dep": "1",
                    "nome": "Financeiro",
                    "integrantes": "5",
                    "carga_horaria": "45"
                }
            ]
        }

## Retornar dados de um departamento [/departamentos/{id_dep}]

*https://private-ca8518-leobossgomes.apiary-mock.com/departamentos/id_dep*

### Metodo GET, parametro id_dep[GET]

+ Parameters
    + id_dep

+ Response 200 (application/json)

        {
            "status": "sucesso",
            "data": {
                "id_dep": "1",
                "nome": "Financeiro",
                "integrantes": "5",
                "carga_horaria": "45"
            }

        }
        
## Inserir departamento [/criadepartamento]

*https://private-ca8518-leobossgomes.apiary-mock.com/criadepartamento*

### Metodo POST [POST]

+ Request (application/json)

        {
            "id_dep": "1",
            "nome": "Financeiro",
            "integrantes": "5",
            "carga_horaria": "45"
        }

+ Response 201 (application/json)

        {
            "status": "sucesso",
            "data": {
                "id_dep": "1",
                "nome": "Financeiro",
                "integrantes": "5",
                "carga_horaria": "45"
            }
        }

## Mudar dados de departamento já existente [/editadepartamento/{id_dep}]

*https://private-ca8518-leobossgomes.apiary-mock.com/editadepartamento/id_dep*

### Metodo PUT, parametro id_dep [PUT]

+ Parameters
    + id_dep

+ Request (application/json)

        {
            "id_dep": "1",
            "nome": "Financeiro",
            "integrantes": "5",
            "carga_horaria": "45"
        }

+ Response 200 (application/json)

        {
            "status": "sucesso",
            "data": {
                "id_dep": "1",
                "nome": "Financeiro",
                "integrantes": "5",
                "carga_horaria": "45"
            }
        }
        
## Excluir Setor [/deletesetor/{id}]

*https://private-ca8518-leobossgomes.apiary-mock.com/deletesetor/id*

### Metodo delete, parametro id [DELETE]

+ Parameters
    + id

+ Request (application/json)

        {
            "nome": "Financeiro",
            "integrantes": "5",
            "carga_horaria": "45"
        }

+ Response 200 (application/json)

        {
            "status": "sucesso",
            "data": {
                "nome": "Financeiro",
                "integrantes": "5",
                "carga_horaria": "45"
            }
        }